// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjavnMnhePIk1td3wKijpasMpY4MHxwlo',
    appId: '1:944111263336:web:4124cb40ca7bb72297e5dd',
    messagingSenderId: '944111263336',
    projectId: 'fir-lab-1-468dd',
    authDomain: 'fir-lab-1-468dd.firebaseapp.com',
    storageBucket: 'fir-lab-1-468dd.firebasestorage.app',
    measurementId: 'G-ZKX5PRFM28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl9KFqFWpjDtG1dgRFeq99fDeOZiQn16Y',
    appId: '1:944111263336:android:731906ebca22fec497e5dd',
    messagingSenderId: '944111263336',
    projectId: 'fir-lab-1-468dd',
    storageBucket: 'fir-lab-1-468dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpH5IN3VAXKeXBKA1gY1vEl9Ju-XUY-w',
    appId: '1:944111263336:ios:f473321b1ac9798f97e5dd',
    messagingSenderId: '944111263336',
    projectId: 'fir-lab-1-468dd',
    storageBucket: 'fir-lab-1-468dd.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );
}
